//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by tuingMgr.rc
//
#define IDC_MYICON                      2
#define IDD_TUINGMGR_DIALOG             102
#define IDC_SIZEHORZ                    102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDC_SIZEVERT                    103
#define IDS_STR_TUINGMGR                103
#define IDB_CLIPTEXTOFF                 104
#define IDB_CLIPTEXTON                  105
#define IDB_LCDTEST                     106
#define IDI_TUINGMGR                    107
#define IDB_CLOSEUP                     107
#define IDI_SMALL                       108
#define IDB_CLOSEDOWN                   108
#define IDC_TUINGMGR                    109
#define IDB_CLOSEHOT                    109
#define IDB_MENUUP                      110
#define IDB_MENUDOWN                    111
#define IDB_MENUHOT                     112
#define IDB_PROPUP                      113
#define IDB_PROPDOWN                    114
#define IDB_PROPHOT                     115
#define IDB_MOVECURSORON                116
#define IDB_MOVECURSOROFF               117
#define IDB_CALCCOPYUP                  118
#define IDB_CALCCOPYDOWN                119
#define IDB_CALCCOPYHOT                 120
#define IDB_COLORTABLE                  121
#define IDB_ONEIMAGE                    122
#define IDB_PLAYDOWN                    123
#define IDB_PLAYHOT                     124
#define IDB_PLAYUP                      125
#define IDB_STOPDOWN                    126
#define IDB_STOPHOT                     127
#define IDR_MAINFRAME                   128
#define IDR_SYSTRAY                     128
#define IDB_STOPUP                      128
#define IDI_DEFAULTPRG                  129
#define IDB_PREVDOWN                    129
#define IDB_PREVHOT                     130
#define IDB_PREVUP                      131
#define IDB_NEXTDOWN                    132
#define IDB_NEXTHOT                     133
#define IDB_NEXTUP                      134
#define IDB_GROUP1UP                    135
#define IDB_GROUP1DOWN                  136
#define IDB_GROUP2DOWN                  137
#define IDB_GROUP2UP                    138
#define IDB_GROUP3DOWN                  139
#define IDB_GROUP3UP                    140
#define IDB_GROUP4DOWN                  141
#define IDB_GROUP4UP                    142
#define IDB_MPADDDOWN                   143
#define IDB_MPADDHOT                    144
#define IDB_MPADDUP                     145
#define IDB_MPCLEARDOWN                 146
#define IDB_MPCLEARHOT                  147
#define IDB_MPCLEARUP                   148
#define IDB_MPRANDOMOFF                 149
#define IDB_MPRANDOMON                  150
#define IDB_TETRIS                      151
#define IDB_SIZEMETER                   152
#define IDB_ENUMFONT                    157
#define IDB_SPY                         158
#define IDD_DDAY                        160
#define IDD_TEXTCLIP                    161
#define IDB_SWAPMOUSEON                 163
#define IDB_SWAPMOUSEOFF                164
#define IDD_LAUNCHER                    165
#define IDD_CALENDAR                    168
#define IDR_POPUPMENU                   300
#define IDD_MAIN                        400
#define IDD_SELWIDGET                   401
#define IDD_SELTIDGET                   402
#define IDD_MOVECURSOR                  403
#define IDD_CPUUSAGE                    404
#define IDD_DISKUSAGE                   405
#define IDD_CLOCK                       406
#define IDD_IMAGESLIDE                  407
#define IDD_MEMO                        408
#define IDC_LIWIDGET                    1030
#define IDC_LIUSEWIDGET                 1039
#define IDC_BTNADDWIDGET                1040
#define IDC_BTNREMOVEWIDGET             1041
#define IDC_BTNUPWIDGET                 1042
#define IDC_BTNDOWNWIDGET               1043
#define IDC_CBBACKCOLOR                 1044
#define IDC_CHKHIDEWIDGET               1045
#define IDC_EDHEIGHT                    1046
#define IDC_SPINHEIGHT                  1047
#define IDC_EDWIDTH                     1048
#define IDC_SPINWIDTH                   1049
#define IDC_CHKSPAN                     1050
#define IDC_RASPANRATIO                 1051
#define IDC_RASPANPIXEL                 1052
#define IDC_EDSPAN                      1053
#define IDC_SPINSPAN                    1054
#define IDC_EDWIDGETDESC                1055
#define IDC_LITIDGET                    1100
#define IDC_LIUSETIDGET                 1101
#define IDC_BTNADDTIDGET                1102
#define IDC_BTNREMOVETIDGET             1103
#define IDC_BTNUPTIDGET                 1104
#define IDC_BTNDOWNTIDGET               1105
#define IDC_CHKHIDETIDGET               1106
#define IDC_EDTIDGETDESC                1107
#define IDC_CLOCKFACE                   1200
#define IDC_CHKHOUR24                   1201
#define IDC_CHKOUTSEC                   1202
#define IDC_CHKDIGIT2                   1203
#define IDC_STBOOT                      1204
#define IDC_CPUTIME1                    1300
#define IDC_CPUTIME2                    1301
#define IDC_CPUTIME3                    1302
#define IDC_CPUTIME4                    1303
#define IDC_CHKVARYAXIS                 1304
#define IDC_CHKVIEWTHREAD               1305
#define IDC_CHKREMOVABLE                1400
#define IDC_CHKNETWORK                  1401
#define IDC_CHKRELATIVECHART            1402
#define IDC_CHKMOVECURSOR               1500
#define IDC_EDMOVECURSORCYCLE           1501
#define IDC_SPINMOVECURSORCYCLE         1502
#define IDC_STMOVECURSORCOUNT           1503
#define IDC_CHKRANDOMSLIDE              1600
#define IDC_CHKDISPLAYFILENAME          1601
#define IDC_CHKMULTIVIEWER              1602
#define IDC_BTNIS_RESET                 1603
#define IDC_BTNIS_DEL                   1604
#define IDC_BTNIS_UP                    1605
#define IDC_BTNIS_DOWN                  1606
#define IDC_LIIMGLIST                   1607
#define IDC_EDIMAGECYCLE                1608
#define IDC_SPINIMAGECYCLE              1609
#define IDC_RAFORMAT1                   1700
#define IDC_RAFORMAT2                   1701
#define IDC_LIFONT                      1702
#define IDC_EDFONTSIZE                  1703
#define IDC_SPINFONTSIZE                1704
#define IDC_CHKWORDWRAP                 1705
#define IDC_EDTITLE                     1706
#define IDC_CBBACK                      1707
#define IDC_CBFORE                      1708
#define IDC_RAVERT                      1800
#define IDC_RAHORZ                      1801
#define IDC_CHKALWAYSONTOP              1802
#define IDC_EDCAPTHICK                  1803
#define IDC_SPINCAPTHICK                1804
#define IDC_CBCAPCOLOR                  1805
#define IDC_EDBDTHICK                   1806
#define IDC_SPINBDTHICK                 1807
#define IDC_CBBDCOLOR                   1808
#define IDC_EDSPLITTHICK                1809
#define IDC_SPINSPLITTHICK              1810
#define IDC_CBSPLITCOLOR                1811
#define IDC_EDTIDGETSIZE                1812
#define IDC_SPINTIDGETSIZE              1813
#define IDC_EDTIDGETGAP                 1814
#define IDC_SPINTIDGETGAP               1816
#define IDC_CBTRAYBACKCOLOR             1817
#define IDC_CBMAINBACKCOLOR             1818
#define IDC_EDTARGETTITLE               1900
#define IDC_EDTARGETYEAR                1901
#define IDC_EDTARGETMONTH               1902
#define IDC_EDTARGETDAY                 1903
#define IDC_CHKDISPLAYHOUR              1904
#define IDC_CHKDISPLAYMINUTE            1905
#define IDC_CHKTEXTCLIP                 2000
#define IDC_CHKAUTOTEXTCLIP             2001
#define IDC_RALAUNCHERICON1             2002
#define IDC_RALAUNCHERICON2             2003
#define IDC_RALAUNCHERICON3             2004
#define IDC_EDLAUNCHERGAP               2005
#define IDC_SPINLAUNCHERGAP             2006
#define IDC_CHKLAUNCHERDISPCAP          2007
#define IDC_RADOCKLEFT                  2008
#define IDC_RADOCKTOP                   2009
#define IDC_RADOCKRIGHT                 2010
#define IDC_RADOCKBOTTOM                2011
#define IDC_RAUNDOCK                    2012
#define IDC_LIANN                       2013
#define IDC_ANNNAME                     2014
#define IDC_CHKANNLUNAR                 2015
#define IDC_CHKANNCONTI                 2016
#define IDC_ANNMONTH                    2017
#define IDC_ANNDAY                      2018
#define IDC_BTNANNADD                   2019
#define IDC_BTNANNDEL                   2020
#define IDC_LITODO                      2021
#define IDC_TODONAME                    2022
#define IDC_TODOMONTH                   2023
#define IDC_TODODAY                     2024
#define IDC_BTNTODOADD                  2025
#define IDC_BTNTODODEL                  2026
#define IDC_TODOYEAR                    2027
#define IDM_ABOUT                       32771
#define ID_SYSTRAYMENU_ABOUT            32774
#define ID_SYSTRAYMENU_TEST1            32775
#define ID_SYSTRAYMENU_TEST2            32776
#define ID_SYSTRAYMENU_P                32777
#define ID_SYSTRAYMENU_ENABLE           32778
#define ID_SYSTRAYMENU_DISABLE          32779
#define TRAYMENU_TEST1                  32780
#define ID_Menu                         32781
#define ID_SYSTRAYMENU_EXIT             32782
#define ID_SYSTRAYMENU_SEP              32783
#define IDM_TEST1                       32784
#define IDM_ENABLE                      32785
#define IDM_DISABLE                     32786
#define IDM_EXIT                        32787
#define IDM_SEP                         32788
#define IDM_TEST2                       32789
#define IDM_ROTATE                      40001
#define IDM_ALWAYSONTOP                 40002
#define IDM_SETTING                     40003
#define IDM_SELWIDGET                   40004
#define IDM_SELTIDGET                   40005
#define IDM_HELP                        40007
#define IDM_CALC_AUTOCOPY               40008
#define IDM_CALC_RESULTUP               40009
#define ID_40010                        40010
#define IDM_LAUNCHER_PROP               40011
#define ID_40012                        40012
#define IDM_LAUNCHER_REMOVE             40013
#define ID_40014                        40014
#define IDM_DOCKLEFT                    40015
#define ID_40016                        40016
#define IDM_DOCKTOP                     40017
#define ID_40018                        40018
#define IDM_DOCKRIGHT                   40019
#define ID_40020                        40020
#define IDM_DOCKBOTTOM                  40021
#define IDM_UNDOCK                      40022
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
